changelog:
  exclude:
    authors:
      - github-actions
    labels:
      - release
  categories:
    - title: New Features
      labels:
        - 'enhancement'
    - title: Bug Fix
      labels:
        - 'bug'
    - title: Other Changes
      labels:
        - '*'
