const apiResponseBlogsList = {
  topics_id: 50,
  ymd: '2023-08-20',
  contents_type: 29,
  contents:
    '<h1>見出し1見出し1見出し1見出し1見出し1見出し1見出し1見出し1見出し1見出し1</h1><h2>見出し2見出し2見出し2見出し2見出し2見出し2見出し2見出し2見出し2見出し2見出し2見出し2見出し2</h2><p>テキストテキスト<strong>太字テキスト</strong>テキスト<i>斜体テキスト</i>テキスト<u>下線テキスト</u>テキスト<a href="https://www.google.co.jp/">リンクテキスト</a>テキスト<a href="https://www.google.co.jp/" target="_blank" rel="noopener noreferrer">リンクテキスト</a>テキストテキストテキストテキストテキスト</p><h3>見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3見出し3</h3><p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p><h4>見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4見出し4</h4><p>テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト</p><figure class="image"><img src="https://afterworks.g.kuroco-img.app/files/user/topics_img/11/ben-o-bro-wpU4veNGnHg-unsplash.jpg"></figure><p>左寄せテキスト</p><p style="text-align:center;">中央寄せテキスト</p><p style="text-align:right;">右寄せテキスト</p><figure class="table"><table><tbody><tr><td>セル1-1</td><td>セル1-2</td><td>セル1-3</td><td>セル1-4</td></tr><tr><td>セル2-1</td><td>セル2-2</td><td>セル2-3</td><td>セル2-4</td></tr><tr><td>セル3-1</td><td>セル3-2</td><td>セル2-3</td><td>セル2-4</td></tr><tr><td>セル4-1</td><td>セル4-2</td><td>セル2-3</td><td>セル2-4</td></tr></tbody></table></figure><ul><li>リスト</li><li>リスト</li><li>リスト</li></ul><ol><li>順序リスト</li><li>順序リスト</li><li>順序リスト</li></ol><blockquote><p>引用引用引用引用引用</p><p>引用引用引用引用引用引用引用引用引用</p></blockquote><pre><code class="language-plaintext">コードブロックコードブロックコードブロックコードブロックコードブロックコードブロック\r\nコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロックコードブロック</code></pre><p>&nbsp;</p>',
  subject:
    '記事本文のコンポーネントを確認できます。タイトルが入ります。タイトルが入ります。タイトルが入ります。タイトルが入ります。タイトルが入ります。',
  topics_flg: 1,
  open_flg: 1,
  regular_flg: 0,
  inst_ymdhi: '2023-08-20T13:34:54+09:00',
  update_ymdhi: '2024-01-06T11:14:50+09:00',
  topics_group_id: 11,
  post_time: '00:00:00',
  slug: '',
  order_no: 0,
  group_nm: 'ブログ（開発）',
  group_description: '',
  contents_type_cnt: 1,
  contents_type_nm: 'ブログ（開発）',
  contents_type_slug: null,
  contents_type_parent_nm: null,
  category_parent_id: null,
  contents_type_ext_col_01: null,
  contents_type_ext_col_02: null,
  contents_type_ext_col_03: null,
  contents_type_ext_col_04: null,
  contents_type_ext_col_05: null,
  tags: [
    {
      tag_id: 35,
      tag_nm: 'ディレクション',
      open_contents_cnt: 11,
      all_contents_cnt: 11,
      inst_ymdhi: '2023-08-20T16:58:22+09:00',
      update_ymdhi: '2023-08-20T16:58:53+09:00',
      tag_category_id: 7,
      tag_comment: null,
      ext_col_01: '',
      ext_col_02: '',
      ext_col_03: '',
      ext_col_04: '',
      ext_col_05: '',
      ext_col_06: '',
      ext_col_07: '',
      ext_col_08: '',
      ext_col_09: '',
      ext_col_10: '',
      weight: 70,
    },
    {
      tag_id: 11,
      tag_nm: 'デザイン',
      open_contents_cnt: 31,
      all_contents_cnt: 31,
      inst_ymdhi: '2023-08-18T19:17:13+09:00',
      update_ymdhi: '2023-08-18T21:05:23+09:00',
      tag_category_id: 7,
      tag_comment: null,
      ext_col_01: '',
      ext_col_02: '',
      ext_col_03: '',
      ext_col_04: '',
      ext_col_05: '',
      ext_col_06: '',
      ext_col_07: '',
      ext_col_08: '',
      ext_col_09: '',
      ext_col_10: '',
      weight: 60,
    },
    {
      tag_id: 12,
      tag_nm: 'コーディング',
      open_contents_cnt: 57,
      all_contents_cnt: 57,
      inst_ymdhi: '2023-08-18T19:17:18+09:00',
      update_ymdhi: '2023-08-18T21:05:23+09:00',
      tag_category_id: 7,
      tag_comment: null,
      ext_col_01: '',
      ext_col_02: '',
      ext_col_03: '',
      ext_col_04: '',
      ext_col_05: '',
      ext_col_06: '',
      ext_col_07: '',
      ext_col_08: '',
      ext_col_09: '',
      ext_col_10: '',
      weight: 40,
    },
  ],
  contents_type_list: [29],
  main_visual: {
    id: '50_ext_01_0',
    url: 'https://afterworks.g.kuroco-img.app/v=1692506094/files/topics/50_ext_1_0.jpg',
    desc: '',
    url_org: 'https://afterworks.g.kuroco-img.app/files/topics/50_ext_1_0.jpg',
  },
  description: '要約が入ります。',
  subject_en:
    'Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title Title',
  description_en: 'description',
  contents_en:
    '<h1>Headline 1 Headline 1 Headline 1 Headline 1 Headline 1 Headline 1 Headline 1 Headline 1 Headline 1 Headline 1</h1><h2>Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2 Headline 2</h2><p>Text Text <strong>Bold Text</strong> Text <i>Italic Text</i> Text <u>Underline Text</u> Text <a href="https://www.google.co.jp/">Link Text</a> Text <a href="https://www.google.co.jp/" target="_blank" rel="noopener noreferrer">Link Text</a> Text Text Text Text Text Text</p><h3>Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3 Headline 3</h3><p>Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text</p><h4>Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4 Headline 4</h4><p>Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text Text</p><figure class="image"><img src="https://afterworks.g.kuroco-img.app/files/user/topics_img/11/ben-o-bro-wpU4veNGnHg-unsplash.jpg"></figure><p>Left-aligned Text</p><p style="text-align:center;">Center-aligned Text</p><p style="text-align:right;">Right-aligned Text</p><figure class="table"><table><tbody><tr><td>Cell 1-1</td><td>Cell 1-2</td><td>Cell 1-3</td><td>Cell 1-4</td></tr><tr><td>Cell 2-1</td><td>Cell 2-2</td><td>Cell 2-3</td><td>Cell 2-4</td></tr><tr><td>Cell 3-1</td><td>Cell 3-2</td><td>Cell 2-3</td><td>Cell 2-4</td></tr><tr><td>Cell 4-1</td><td>Cell 4-2</td><td>Cell 2-3</td><td>Cell 2-4</td></tr></tbody></table></figure><ul><li>List</li><li>List</li><li>List</li></ul><ol><li>Ordered List</li><li>Ordered List</li><li>Ordered List</li></ol><blockquote><p>Quote Quote Quote Quote Quote</p><p>Quote Quote Quote Quote Quote Quote Quote Quote Quote</p></blockquote><pre><code class="language-plaintext">Code Block Code Block Code Block Code Block Code Block Code Block\r\nCode Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block Code Block</code></pre><p>&nbsp;</p>',
}

const apiResponseBlogsPageInfo = {
  totalCnt: 16,
  perPage: 20,
  totalPageCnt: 1,
  pageNo: 1,
  firstIndex: 1,
  lastIndex: 16,
  path: '/rcms-api/6/blogs',
  param: '?data_format=json',
  startPageNo: 1,
  endPageNo: 1,
}

const apiResponseBlogs = {
  errors: [],
  messages: [],
}

export type ApiResponseBlogsData = typeof apiResponseBlogsList

export type ApiResponseBlogsPageInfo = typeof apiResponseBlogsPageInfo

export type ApiResponseBlogs = {
  list: ApiResponseBlogsData[]
  pageInfo: ApiResponseBlogsPageInfo
} & typeof apiResponseBlogs
