name: push

on:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'
jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/app/frontend
    steps:
      - uses: actions/checkout@v2
        # with:
        # ref: develop

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn prettier
      - run: yarn stylelint
      - run: yarn lint:quiet
      - run: yarn typecheck
      - run: yarn test
      - name: build
        run: |
          yarn run build
