name: push

on:
  push:
    branches:
      - '**'
env:
  cache-version: v1
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      npm-cache-dir-path: ${{ steps.npm-cache-dir-path.outputs.dir }}
    defaults:
      run:
        working-directory: src/app/frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ env.cache-version }}-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-npm-

      - run: npm ci

  lint:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: src/app/frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.npm-cache-dir-path }}
          key: ${{ env.cache-version }}-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-npm-

      - run: npm ci
      - run: npm run format
      - run: npm run stylelint
      - run: npm run lint-quiet
      - run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    needs: setup
    defaults:
      run:
        working-directory: src/app/frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.npm-cache-dir-path }}
          key: ${{ env.cache-version }}-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-npm-

      - run: npm ci
      - run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [setup, lint, test]
    defaults:
      run:
        working-directory: src/app/frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ needs.setup.outputs.npm-cache-dir-path }}
          key: ${{ env.cache-version }}-${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ env.cache-version }}-${{ runner.os }}-npm-

      - run: npm ci
      - name: Build
        run: npm run build
